Dependency to ocamlgraph corrected

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -884,7 +884,7 @@ esac
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd $ac_popdir
+    cd "$ac_popdir"
   done
 fi
 
@@ -2539,8 +2539,8 @@ fi
 
 
 for module in Flow; do
-    echo "$as_me:$LINENO: checking for graph ($module)" >&5
-echo $ECHO_N "checking for graph ($module)... $ECHO_C" >&6
+    echo "$as_me:$LINENO: checking for ocamlgraph ($module)" >&5
+echo $ECHO_N "checking for ocamlgraph ($module)... $ECHO_C" >&6
 cat > conftest.ml <<EOF
 open $module
 EOF
@@ -2550,7 +2550,7 @@ EOF
     else
 	unset found
         if ! test "$use_findlib" = no ; then
-	    if check_inc=`$OCAMLFIND query -i-format graph 2>/dev/null`; then
+	    if check_inc=`$OCAMLFIND query -i-format ocamlgraph 2>/dev/null`; then
 		if $OCAMLC -c $MODULE_INCLUDES $check_inc conftest.ml > /dev/null 2>&1 ; then
 		    MODULE_INCLUDES="$MODULE_INCLUDES $check_inc"
 		    result="adding $check_inc"
@@ -2559,7 +2559,7 @@ EOF
 	    fi
 	fi
 	if ! test "$found"; then
-	    for check_dir in  $SITELIBDIR/graph; do
+	    for check_dir in  $SITELIBDIR/ocamlgraph; do
 		if $OCAMLC -c -I $check_dir conftest.ml > /dev/null 2>&1 ; then
 		    MODULE_INCLUDES="$MODULE_INCLUDES -I $check_dir"
 		    result="adding -I $check_dir"
@@ -2572,15 +2572,15 @@ EOF
 
 
     if test "$found" ; then
-		if ! $OCAMLC -o conftest $MODULE_INCLUDES graph.cma conftest.cmo > /dev/null 2>&1 ; then
-		    echo "$as_me:$LINENO: result: graph.cma not found" >&5
-echo "${ECHO_T}graph.cma not found" >&6
-		    { { echo "$as_me:$LINENO: error: Required library graph not found" >&5
-echo "$as_me: error: Required library graph not found" >&2;}
+		if ! $OCAMLC -o conftest $MODULE_INCLUDES ocamlgraph.cma conftest.cmo > /dev/null 2>&1 ; then
+		    echo "$as_me:$LINENO: result: ocamlgraph.cma not found" >&5
+echo "${ECHO_T}ocamlgraph.cma not found" >&6
+		    { { echo "$as_me:$LINENO: error: Required library ocamlgraph not found" >&5
+echo "$as_me: error: Required library ocamlgraph not found" >&2;}
    { (exit 1); exit 1; }; }
 		else
-		    if ! echo "$EXTRA_CMA" | grep "graph.cma" > /dev/null 2>&1 ; then
-			EXTRA_CMA="$EXTRA_CMA graph.cma"
+		    if ! echo "$EXTRA_CMA" | grep "ocamlgraph.cma" > /dev/null 2>&1 ; then
+			EXTRA_CMA="$EXTRA_CMA ocamlgraph.cma"
 		    fi
 		    echo "$as_me:$LINENO: result: $result" >&5
 echo "${ECHO_T}$result" >&6
@@ -2588,8 +2588,8 @@ echo "${ECHO_T}$result" >&6
     else
 		echo "$as_me:$LINENO: result: not found" >&5
 echo "${ECHO_T}not found" >&6
-		{ { echo "$as_me:$LINENO: error: Required module $module not found in library graph" >&5
-echo "$as_me: error: Required module $module not found in library graph" >&2;}
+		{ { echo "$as_me:$LINENO: error: Required module $module not found in library ocamlgraph" >&5
+echo "$as_me: error: Required module $module not found in library ocamlgraph" >&2;}
    { (exit 1); exit 1; }; }
     fi
 done
@@ -3467,11 +3467,6 @@ esac
   *) ac_INSTALL=$ac_top_builddir$INSTALL ;;
   esac
 
-  if test x"$ac_file" != x-; then
-    { echo "$as_me:$LINENO: creating $ac_file" >&5
-echo "$as_me: creating $ac_file" >&6;}
-    rm -f "$ac_file"
-  fi
   # Let's still pretend it is `configure' which instantiates (i.e., don't
   # use $as_me), people would be surprised to read:
   #    /* config.h.  Generated by config.status.  */
@@ -3510,6 +3505,12 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
 	 fi;;
       esac
     done` || { (exit 1); exit 1; }
+
+  if test x"$ac_file" != x-; then
+    { echo "$as_me:$LINENO: creating $ac_file" >&5
+echo "$as_me: creating $ac_file" >&6;}
+    rm -f "$ac_file"
+  fi
 _ACEOF
 cat >>$CONFIG_STATUS <<_ACEOF
   sed "$ac_vpsub
